name: basic-actions
run-name: ${{ github.actor }} just pushed.
on: [push]
jobs:
  check_mysql:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:9.6.0
        env:
          MYSQL_DATABASE: NutriLog
          MYSQL_ROOT_PASSWORD: Barker123!
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v6.0.2
      - run: pip install -r ./requirements.txt
      - run: python3 ./RobertSUcks/createDB.py
                
